### ISSUE TITLE
Export to Anki causing crash

### ISSUE THREAD

**Issue by Jpcomben** [mvysny/aedict#723]
I have used aedict many times to record words in srs that I want to memorise. It's always worked flawlessly and been one of the best features for me. 

I hadn't used this function in a while but when I tried today, it caused an 'unfortunately, aedict has stopped error'. It repeats the error every time. I've tried different words too. 

Running on a Nexus 5, Android 6.0.1. 

Is this a known bug or is it just me having an issue? 

Thanks.

**Comment by mvysny** [comment]
Thank you for letting me know. I can see the crash in my Google Play Console, it is exactly the same as #689. It is a security error which says that Aedict can not access AnkiDroid to add stuff to it. Which is weird, because Aedict has the necessary permission to do so. I thought I have fixed that, but apparently it still crashes on your phone. I'll ask the AnkiDroid guys for help. 

Meanwhile, could you please try to reinstall Aedict3 and/or AnkiDroid, so that we can rule out the possibility that this is a some Android glitch on your phone?

**Comment by Jpcomben** [comment]
Thanks for the quick response. I followed your suggestion and reinstalled both apps but unfortunately the problem persists. I hope you can find a resolution. Thanks for looking into this.

**Comment by mvysny** [comment]
Could you please check that you have the newest Aedict3 (3.39.27) installed?

**Comment by mvysny** [comment]
If yes, I have created the AnkiDroid issue, as 1. exporting to AnkiDroid works for me flawlessly, and 2. I have checked that Aedict3 asks for necessary permission. This may still be Android issue though...
Anyway, please head here: https://github.com/ankidroid/Anki-Android/issues/4544
And please provide the debug info from your phone: https://ankidroid.org/docs/help.html

**Comment by timrae** [comment]
@Jpcomben
In addition to the debug info, any other info that might be relevant such as phone make/model, any custom ROM etc might also be useful for figuring out the issue.

**Comment by Jpcomben** [comment]
Hey,

Thanks for the ongoing support. I am using the latest version of aedict. My
phone make is Nexus 5, running stock android 6.0.1. No custom roms.

My debug info is...

AnkiDroid Version = 2.7

Android Version = 6.0.1

ACRA UUID = 2d50cc2b-17e5-46e3-b1ad-f8aca3bc6d8a

I will copy this into the github thread too.

Thanks,

James

**Comment by mvysny** [comment]
From the bug opened at Ankidroid side it is clear that your phone security settings disable aedict access to Ankidroid. Unfortunately there's nothing I can do here. Closing this bug as won't fix.

**Comment by Jpcomben** [comment]
I'm really sorry for wasting both of your time. I don't know how the
permissions got revoked, I certainly didn't do it wittingly.

Thanks for your help.

**Comment by mvysny** [comment]
No worries. It is good to have this bug documented. Others may Google for it and learn that this issue may be caused by a phone misconfiguration.

**Comment by aedicted** [comment]
I recently updated my Samsung Galaxy S7 (G930FD) to Nougat (G930FXXU1DQAS) where Aedict continuously kept crashing whenever I tried to export something to AnkiDroid. Thanks to the developer's help, that issue could be easily fixed by enabling the additional permission to read and write the AnkiDroid database in the corresponding permission setting.

Although I'm not convinced that this is related, once I further updated to yet a newer Nougat version (G930FXXU1DQB3), I had the same issue with the difference that the permission option wasn't sticky anymore. Once I left the settings menu, the slider of the permission was put to "off" every time I checked again and Aedict kept crashing during the export attempt.

To do a little testing, I uninstalled AnkiDroid, reinstalled the older version 2.7 instead and to my surprise, the export from Aedict continued to work again - that even after I updated AnkiDroid back to the current version 2.8.1. I'm far from being able to understand that behavior, but as per the developer's request, I wanted to state it here so others might be able to contribute and share their experiences.

**Comment by timrae** [comment]
I've also occasionally observed such behaviour, I can only assume it's an Android bug.

**Comment by mvysny** [comment]
@aedicted thanks, this is valuable info! I am also led to believe that this is actually a bug in Android, auto-reverting custom permissions (permissions declared by apps such as AnkiDroid), since built-in permissions (such as SD-Card Read+Write permission) are not reverted.

Of course this should be fixed Android side, but that's just plain impossible with 10000+ devices. Not to mention that generally Android phone vendors generally do not give a damn. Have you seen any phone vendor (the big ones) to have a bug tracker? :-D

One possible workaround would be for Aedict to target API 23 and start asking for permissions on demand: https://developer.android.com/training/permissions/requesting.html . However, the dictionaries may be stored on the SD Card at any location, and thus I would have to ask for user's permission every time I need to do a dictionary search. Asking for user's permission introduces an indirection (since the API is really shitty, shame on you Google), and dictionary search is performed from a lot of places. Implementing this would fill the Aedict code with indirections, which is basically a recipe for spaghetti, unmaintainable code and a total disaster. I'd like to avoid that. Hmm, or maybe I just could be able to devise some clever threading 

Another workaround is for @timrae to stop asking for that particular permission. Of course that would mean a security hole since any app would be able to change AnkiDroid decks without user's consent. So it's probably not going to happen.
